### ISSUE TITLE
[BUG] Receiving Desktop Notifications Fails with Type Error

### ISSUE THREAD

**Issue by adimit** [muniter/halinuxcompanion#35]
**Describe the bug**
Sending a notification from HA to my desktop PC doesn't work as the companion runs into a type error.

**To Reproduce**
- Installed the master version of `halinuxcompanion`
- Installed following the instructions, I'm using `pyenv` to set the python version to `3.12.8` (`3.13` which is what I normally use, doesn't install, as the dependent versions of `pydantic` and `greenlet` aren't compatible)
- Started `halinuxcompanion` with the following config:
```json
{
  "ha_url": "http://raspberrypi:8123/",
  "ha_token": "my_token",
  "device_id": "desktop_pc",
  "device_name": "Destkop PC",
  "manufacturer": "",
  "model": "Computer",
  "computer_ip": "192.168.178.xx",
  "computer_port": 8400,
  "refresh_interval": 15,
  "loglevel": "INFO",
  "sensors": {
    "cpu": {
      "enabled": true,
      "name": "CPU"
    },
    "memory": {
      "enabled": true,
      "name": "Memory Load"
    },
    "uptime": {
      "enabled": true,
      "name": "Uptime"
    },
    "status": {
      "enabled": true,
      "name": "Status"
    }
  },
  "services": {
    "notifications": {
      "enabled": true,
      "url_program": "xdg-open",
      "commands": {
        "command_suspend": {
          "name": "Suspend",
          "command": ["systemctl", "suspend"]
        },
        "command_poweroff": {
          "name": "Power off",
          "command": ["systemctl", "poweroff"]
        },
        "command_reboot": {
          "name": "Reboot",
          "command": ["systemctl", "reboot"]
        },
        "command_hibernate": {
          "name": "Hibernate",
          "command": ["systemctl", "hibernate"]
        },
        "command_open_ha": {
          "name": "Open Home Assistant",
          "command": ["xdg-open", "http://raspberrypi:8123/"]
        }
      }
    }
  }
}
```

- Send a notification with the following template from HA
```yaml
alias: Test
description: ""
triggers: []
conditions: []
actions:
  - action: notify.mobile_app_destkop_pc
    metadata: {}
    data:
      message: Elo
      title: Blubb
mode: single
```

**Expected behavior**
Notification should be sent to DBUS

**Application Logs**

- Log output:
```
INFO:halinuxcompanion.notifier:Received notification request:{'message': 'Elo', 'title': 'Blubb', 'push_token': '866841e2083faea3b8ec830486dceb471715d08c6e600b23aecc0fe125911e4e', 'registration_info': {'app_id': 'Linux_Companion0.0.1', 'app_version': '0.0.1', 'webhook_id': '58061f0f0743b744d330211725cfa6009726072a3e32152cce0a3431d86dc7c6', 'os_version': '6.12.6-arch1-1'}}
INFO:aiohttp.access:192.168.178.44 [26/Dec/2024:12:45:06 +0100] "POST /notify HTTP/1.1" 201 199 "-" "HomeAssistant/2024.12.5 aiohttp/3.11.11 Python/3.13"
INFO:halinuxcompanion.notifier:Sending dbus notification
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-19' coro=<Notifier.dbus_notify() done, defined at /home/aleks/var/src/halinuxcompanion/halinuxcompanion/notifier.py:305> exception=SignatureBodyMismatchError('DBus STRING type "s" must be Python type "str", got <class \'pathlib.PosixPath\'>')>
Traceback (most recent call last):
  File "/home/aleks/var/src/halinuxcompanion/halinuxcompanion/notifier.py", line 316, in dbus_notify
    id = await self.interface.call_notify(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aleks/var/src/halinuxcompanion/.venv/lib/python3.12/site-packages/dbus_next/aio/proxy_object.py", line 79, in method_fn
    msg = await self.bus.call(
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/aleks/var/src/halinuxcompanion/.venv/lib/python3.12/site-packages/dbus_next/aio/message_bus.py", line 303, in call
    self._call(msg, reply_handler)
  File "/home/aleks/var/src/halinuxcompanion/.venv/lib/python3.12/site-packages/dbus_next/message_bus.py", line 588, in _call
    self.send(msg)
  File "/home/aleks/var/src/halinuxcompanion/.venv/lib/python3.12/site-packages/dbus_next/aio/message_bus.py", line 326, in send
    self._writer.schedule_write(msg, future)
  File "/home/aleks/var/src/halinuxcompanion/.venv/lib/python3.12/site-packages/dbus_next/aio/message_bus.py", line 82, in schedule_write
    self.buffer_message(msg, future)
  File "/home/aleks/var/src/halinuxcompanion/.venv/lib/python3.12/site-packages/dbus_next/aio/message_bus.py", line 78, in buffer_message
    (msg._marshall(negotiate_unix_fd=self.negotiate_unix_fd), copy(msg.unix_fds), future))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aleks/var/src/halinuxcompanion/.venv/lib/python3.12/site-packages/dbus_next/message.py", line 215, in _marshall
    body_block = Marshaller(self.signature, self.body)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aleks/var/src/halinuxcompanion/.venv/lib/python3.12/site-packages/dbus_next/_private/marshaller.py", line 8, in __init__
    self.signature_tree.verify(body)
  File "/home/aleks/var/src/halinuxcompanion/.venv/lib/python3.12/site-packages/dbus_next/signature.py", line 359, in verify
    type_.verify(body[i])
  File "/home/aleks/var/src/halinuxcompanion/.venv/lib/python3.12/site-packages/dbus_next/signature.py", line 283, in verify
    self._verify_string(body)
  File "/home/aleks/var/src/halinuxcompanion/.venv/lib/python3.12/site-packages/dbus_next/signature.py", line 196, in _verify_string
    raise SignatureBodyMismatchError(
dbus_next.errors.SignatureBodyMismatchError: DBus STRING type "s" must be Python type "str", got <class 'pathlib.PosixPath'>
```

**Home Assistant Logs**
Everything seems alright on the home assistant side.

**Additional context**
I'm running Arch Linux. Globally installed DBus versions are:

```
dbus 1.14.10-2
dbus-broker 36-4
dbus-broker-units 36-4
kdbusaddons 6.9.0-1
lib32-dbus 1.14.10-2
libdbusmenu-glib 16.04.0.r498-2
libdbusmenu-gtk3 16.04.0.r498-2
python-dbus 1.3.2-5
sdbus-cpp 2.1.0-2
xdg-dbus-proxy 0.1.6-1
```

Introspection of my dbus' notify endpoint is this:
```
method call time=1735214725.904123 sender=:1.61 -> destination=:1.12 serial=9 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "notify-send"
   uint32 0
   string ""
   string "Foo"
   string ""
   array [
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 1
      )
      dict entry(
         string "sender-pid"
         variant             int64 46711
      )
   ]
   int32 -1
```

Using `dbus-monitor`

**Comment by muniter** [comment]
Nice catch! Thank you, just merged the PR
